title: Panagiotis Beligiannis
logo: /assets/images/profile.jpg
description: >
  IT professional with hands-on experience in software development, web development, 
  cloud technologies, and data security.
show_downloads: false
theme: jekyll-theme-minimal

# Navigation
header_pages:
  - about.md
  - education.md
  - experience.md
  - skills.md
  - certifications.md
  - languages.md

# About
email: belips@gmx.com
phone: +306940539838
website: "https://github.com/PanagiotisBeligiannis"
linkedin: "panagiotis-beligiannis-7973b033b"
github: "PanagiotisBeligiannis"

# Build settings
markdown: kramdown
permalink: pretty